class Features(object):
    Face_count = 'face_count'
    Rot_distance = 'rot_distance'
    Face_bb = 'face_bb'
    Tilted_edges = 'tilted_edges'
    Edge_hist = 'edge_hist'
    Hsv_hist = 'hsv_hist'
    DenseSIFT_L0 = 'denseSIFT_L0'
    DenseSIFT_L1 = 'denseSIFT_L1'
    DenseSIFT_L2 = 'denseSIFT_L2'
    Hog_L0 = 'hog_L0'
    Hog_L1 = 'hog_L1'
    Hog_L2 = 'hog_L2'
    Lbp_L0 = 'lbp_L0'
    Lbp_L1 = 'lbp_L1'
    Lbp_L2 = 'lbp_L2'
    Gist = 'gist'
